--------------------------------------------------------
--  Fichier créé - lundi-avril-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEDICAMENT
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."MEDICAMENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"MALADIE" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YOUSSEF.MEDICAMENT
SET DEFINE OFF;
Insert into YOUSSEF.MEDICAMENT (ID,NOM,TYPE,PRIX,MALADIE,QUANTITE) values ('16ykk','16ykk','16ykk','16ykk','16ykk','16ykk');
Insert into YOUSSEF.MEDICAMENT (ID,NOM,TYPE,PRIX,MALADIE,QUANTITE) values ('16ykkk','16ykkk','16ykkk','16ykkk','16ykkk','16ykkk');
Insert into YOUSSEF.MEDICAMENT (ID,NOM,TYPE,PRIX,MALADIE,QUANTITE) values ('123y','123y','123y','123y','123yk','123y');
Insert into YOUSSEF.MEDICAMENT (ID,NOM,TYPE,PRIX,MALADIE,QUANTITE) values ('aaaaa','ykyk','aaaaa','aaaaa','aaaaa','aaaaa');
--------------------------------------------------------
--  DDL for Index MEDICAMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."MEDICAMENT_PK" ON "YOUSSEF"."MEDICAMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEDICAMENT
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."MEDICAMENT" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MEDICAMENT" MODIFY ("MALADIE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MEDICAMENT" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MEDICAMENT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MEDICAMENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MEDICAMENT" ADD CONSTRAINT "MEDICAMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOUSSEF"."MEDICAMENT" MODIFY ("ID" NOT NULL ENABLE);
